### ISSUE TITLE
JSON ParseException

### ISSUE THREAD

**Issue by AirPenn** [download13/Mineshafter-Launcher#19]
First, thank you for all your hard work on this program.

RIP google group: I first reported this issue back in march, but apparently only one other person had this issue and no one had any solutions.

1) Yes I have tried deleting .minecraft.  Did not fix.
2) Yes I am using the latest mineshafter version.
3) Yes I have tried using different versions of minecraft & forge.

When I run minecraft without forge, everything works fine.  When I run minecraft with forge (mods folder empty), the game crashes while loading single-player worlds.  It gives an extensive crash report and game output log, thankfully: [(pastebin)](https://pastebin.com/pkXYMFs9)

One interesting thing in that report is that in Mineshafter-Launcher/src/info/mineshafter/datasources/MineshafterProfileAuthority.java, the code on line 51 fails: `JsonObject pj = JsonObject.readFrom(profileJSON);`  But why?  Look at the game output:
```
[main/INFO] [STDOUT]: [info.mineshafter.datasources.MineshafterProfileAuthority:getProfile:47]: MS.getProfile: <html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

So one of the files on the mineshafter.info website is returning HTTP error 302.
This file: https://mineshafter.info/mcapi/profile

But here's the kicker: when I run mineshafter without forge, it works, despite the error.  The game output still has the "302 found" output, but no JSON exception.

OS: Windows 8.1 64-bit
Java: 1.8
Minecraft: error over many versions, but let's say 1.12.2
Forge version: 14.23.0.2503

I hope this is enough information to solve the issue.  It has been very tedious not being able to use worldedit for six months.  If you have any questions, feel free to ask.

Cheers,
-AP

**Comment by download13** [comment]
I've fixed the problem, I think. The only issue is it seems to only work once you've cleared the HTTP cache which I'm not sure how to do for Java.

Try using the control panel -> internet settings -> clear cache function and see if that does it

**Comment by AirPenn** [comment]
Thanks for the quick response!

I deleted the Java cache, and also the temp files for Windows and IE, and all the IE history files.  It unfortunately still does not work.  I'm not really familiar with Java too much....  Would resetting the winsock catalog do anything?

**Comment by download13** [comment]
That's the only stuff I know of. I tried modifying the server configuration again so that the server will try to ignore any content you've already cached. Is it working any better now?

**Comment by AirPenn** [comment]
Aaaand, nope.  Google might have a few ideas.  Would setting a `cache-control: no-cache` header do anything?

And potentially relevent SO posts:
https://stackoverflow.com/questions/31843955/httpurlconnection-keeping-cache
https://stackoverflow.com/questions/34534945/java-httpurlconnection-returns-cached-response-every-time

**Comment by download13** [comment]
As it is, I have nginx forcing `Cache-Control: no-store, no-cache`, deleting `If-Modified-Since` and `If-None-Match` from the request, and deleting `ETag` and `Last-Modified` from the response.

So there should be no possible way for a caching error to be the culprit at this point.

Though it occurs to me now that I was initially under the impression that the problem was a 304 response when it's actually a 302. This leads me to believe that your client is connecting to the HTTP endpoint when it needs to connect to HTTPS (since that's the only case where 302 would be returned).

So [heres](https://transfer.sh/pPXmD/Mineshafter-launcher.jar) a fresh version of the launcher you can try. If that solves the issue I'll push it out on the site.

**Comment by AirPenn** [comment]
Thanks again for the quick response!

Unfortunately, it did not work.  Same JSON parser exception, same 302 error.  I'll do some more googling tomorrow.

**Comment by download13** [comment]
You said it works without forge? I wonder if forge is somehow forcing HTTP mode on all requests.

**Comment by AirPenn** [comment]
We might be on to something.  The 302 error happens whether or not forge is there.  Perhaps Forge is forcing a crash when it detects an error.

I just noticed something by comparing the game output with and without forge.  With forge, this is printed:
`[15:49:55] [main/INFO] [STDOUT]:
 [info.mineshafter.datasources.MineshafterProfileAuthority:getProfile:47]: MS.getProfile:`
and without, this is printed:
`[09:29:38] [pool-2-thread-1/INFO]: [STDOUT]: MS.getProfile:`
Notice how with forge is `[main/INFO]` and without is `[pool-2-thread-1/INFO]`.  Could this have anything to do with anything?

**Comment by download13** [comment]
I just noticed that the output it's giving `[info.mineshafter.datasources.MineshafterProfileAuthority:getProfile:47]: MS.getProfile:` no longer exists in the latest version and the parsing doesn't happen until after line 51.  I wonder if you're somehow still on an older version of the launcher. One that still uses HTTP to access the mineshafter api.

In the .minecraft directory there should be `launcher_mcpatched.jar` and `ms-starter.jar`. Can you delete those? Maybe it's somehow not refreshing them when it starts.

[Here's](https://transfer.sh/EVD5y/Mineshafter-launcher.jar) another new version that adds exception handling for the parser. At the very least it should just not show a skin instead of crashing.

See if you can get new debug output from this one and we'll go from there.

**Comment by AirPenn** [comment]
Hm, I was just using the version you gave to me yesterday.  Anyway, after deleting those files, the game doesn't launch, and game output. `launcher_mcpatched.jar` does update every time, but `ms-starter.jar` does not.  When the game starts, no `ms-starter.jar` is created in `.minecraft`.  In fact, the last time the file was modified was October 26th, 2016.  It launches properly if I drop that file back in (but still has the crash).

The new version still crashes with the same JSON exception.  Here's the game output: https://pastebin.com/9j3xt4HF

By the way, the launcher title is `Minecraft Launcher 1.6.84-j`, and has a red warning label: "You are running an old version of the launcher.  Please consider using the new launcher, which will improve the performance of both launcher and game."

**Comment by download13** [comment]
That's a message that get displayed now if you use the java launcher instead of their new windows exe launcher.

If it's not recreating the ms-starter.jar file that would explain the problem. ms-starter is what actually runs when the game runs. It's basically just a copy of the launcher jar but it's in a known place (.minecraft).

If it was happening only with forge then the problem should've been solved by the times you ran it without forge. Forge is probably just making the exceptions fatal like you said.

What's the output for running it without forge, and with the ms-starter.jar file deleted? If it encounters an error it should at least say something like "This jar file not found: Unable to create ms-starter.jar".

On a side note: do you have any antivirus software running that could be locking files?

**Comment by AirPenn** [comment]
Here's the launcher log without forge and without ms-starter: https://pastebin.com/yhndAzyf

The relevant part:
```
[19:07:25 FATAL]: Fatal error launching game. Report this to http://bugs.mojang.com please!
java.lang.RuntimeException: Classpath file not found: C:\Users\[...]\AppData\Roaming\.minecraft\ms-starter.jar
    at net.minecraft.launcher.game.MinecraftGameRunner.constructClassPath(MinecraftGameRunner.java:392) ~[launcher_mcpatched.jar:1.6.84-j]
    at net.minecraft.launcher.game.MinecraftGameRunner.createArgumentsSubstitutor(MinecraftGameRunner.java:299) ~[launcher_mcpatched.jar:1.6.84-j]
    at net.minecraft.launcher.game.MinecraftGameRunner.launchGame(MinecraftGameRunner.java:168) ~[launcher_mcpatched.jar:1.6.84-j]
    at com.mojang.launcher.game.runner.AbstractGameRunner.onDownloadJobFinished(AbstractGameRunner.java:186) [launcher_mcpatched.jar:1.6.84-j]
    at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:122) [launcher_mcpatched.jar:1.6.84-j]
    at com.mojang.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher_mcpatched.jar:1.6.84-j]
    at com.mojang.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:86) [launcher_mcpatched.jar:1.6.84-j]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

Regarding the antivirus, I do have it running, but I just put the .minecraft directory on the exclusion list and it didn't make a difference, so I doubt it had anything to do with it.

**Comment by download13** [comment]
You could take the latest launcher I sent, rename it to ms-starter.jar, and put it into `.minecraft`. That wouldn't tell us why the launcher can't copy itself, but it might fix your problem.

**Comment by AirPenn** [comment]
This "fixes" the problem.  With forge, the world opens fine, and there's not 302 error.  So basically every time there's a new version of mineshafter I'll just copy and paste it into `.minecraft` as `ms-starter.jar`.  I have no idea why it isn't copying automatically though.

Thank you so much for your help!

**Comment by download13** [comment]
You're welcome, I guess. Maybe someday I'll be able to fix the underlying problem.
